### ISSUE TITLE
errorr

### ISSUE THREAD

**Issue by zebooooo** [Frogleim/spotify_bot_streamer#6]
Traceback (most recent call last):
  File "firebase_db.py", line 5, in <module>
    cred = credentials.Certificate("./spotify-streamer-18cc3-firebase-adminsdk-us15t-2e400350e5.json")
  File "C:\Users\tasar\AppData\Roaming\Python\Python38\site-packages\firebase_admin\credentials.py", line 83, in __init__
    with open(cert) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: './spotify-streamer-18cc3-firebase-adminsdk-us15t-2e400350e5.json'

**Comment by Frogleim** [comment]
You , should you use your own firebase key, I'm working on to replace  firebase to basic SQl, now
